# Generated by Django 4.2.7 on 2023-11-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('anio_auto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_producto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('numero_contacto', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=200)),
                ('direccion_vivienda', models.CharField(max_length=200)),
                ('autos', models.ManyToManyField(blank=True, null=True, to='taller.auto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('numero_contacto', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=200)),
                ('direccion_vivienda', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_civil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rubro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField(default=0)),
                ('ciudad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_empleado',
            fields=[
                ('id_tipo_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_empleado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField(default=1)),
                ('imagenUrl', models.ImageField(upload_to='imagenesServicios')),
                ('encargado', models.ManyToManyField(to='taller.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(default=0)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_realizar', models.DateField()),
                ('FK_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=200)),
                ('informacion_extra', models.CharField(blank=True, max_length=200, null=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagenUrl', models.ImageField(upload_to='imagenesProducto')),
                ('stock', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.categoria_producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.estado_civil'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.tipo_empleado'),
        ),
        migrations.CreateModel(
            name='Detalle_reserva',
            fields=[
                ('id_detalle_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('FK_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.servicio')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.reserva')),
            ],
        ),
    ]
