# Generated by Django 4.2.7 on 2023-11-20 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('anio_auto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_producto',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('numero_contacto', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=200)),
                ('direccion_vivienda', models.CharField(max_length=200)),
                ('autos', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('numero_contacto', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=200)),
                ('direccion_vivienda', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_civil',
            fields=[
                ('id_estado_civil', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('precio', models.IntegerField(default=0)),
                ('fecha_atencion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_taller', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField(default=0)),
                ('ciudad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_empleado',
            fields=[
                ('id_tipo_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_empleado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('FK_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField(default=1)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagenUrl', models.ImageField(upload_to='imagenesProducto')),
                ('stock', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.categoria_producto')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.estado_civil'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.tipo_empleado'),
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id_detalle_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('FK_id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.venta')),
                ('FK_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_reserva',
            fields=[
                ('id_detalle_reserva', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('FK_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.servicio')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.reserva')),
            ],
        ),
    ]
