# Generated by Django 4.2.7 on 2023-11-22 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='encargado',
        ),
        migrations.AddField(
            model_name='servicio',
            name='encargado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taller.empleado'),
            preserve_default=False,
        ),
    ]
