# Generated by Django 4.2.7 on 2023-11-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="estado_civil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taller.estado_civil",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="taller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taller.taller",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tipo_empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taller.tipo_empleado",
            ),
        ),
    ]
