# Generated by Django 4.2.7 on 2023-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='id',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id_servicio',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
