# Generated by Django 4.2.7 on 2023-11-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_remove_auto_id_remove_cliente_id_remove_taller_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_empleado',
            name='id_tipo_empleado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
