# Generated by Django 4.2.7 on 2023-11-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taller", "0003_auto_duenio_reserva_fk_cliente_servicio_encargado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="estado_civil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taller.estado_civil",
            ),
        ),
    ]
