# Generated by Django 4.2.7 on 2023-11-20 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_tipo_empleado_id_tipo_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='FK_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taller.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
