# Generated by Django 4.2.7 on 2023-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_reserva_fk_cliente_venta_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='total',
            new_name='valor_total',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='valor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
