# Generated by Django 4.2.7 on 2023-11-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_rename_total_venta_valor_total_detalle_venta_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='valor_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
